name: pin_tunnel_application_production
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  supabase_flutter: ^1.10.3
  provider: ^6.0.5
  dart_either: ^1.0.0
  timezone: ^0.9.2
  mocktail: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_local_notifications: ^15.1.1
  sign_in_with_apple: ^4.3.0
  onesignal_flutter: ^5.0.0
  bloc_test: ^9.1.4
  fl_chart: ^0.63.0
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.5.0
  syncfusion_flutter_charts: ^22.2.12
  flutter_jailbreak_detection: ^1.10.0
  dotted_border: ^2.0.0+3
  google_fonts: ^6.0.0
  url_launcher: ^6.1.14
  connectivity_plus: ^4.0.2
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/brandmark-design_1.png
    - assets/brandmark-design.png
    - assets/temperature_sensor.png
    - assets/smoke_sensor.png
    - assets/laser_actuator.png
    - assets/pintunnel_image.png
    - assets/actuator.gif
    - assets/sensor.gif