name: Testing Workflow

on:
    push:
        branches: ["development"]
    
    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                flutter-version: 'stable'
            - name: Install dependencies
              run: flutter pub get
            - name: Flutter tests
              run: flutter test
